services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop
    volumes:
      - ./src/main/resources/sql/data:/docker-entrypoint-initdb.d/data
      - ./src/main/resources/sql/schema:/docker-entrypoint-initdb.d/schema
    ports:
      - "5432:5432"
